# Generated by Django 3.2.23 on 2024-01-27 11:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20240127_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=tinymce.models.HTMLField(max_length=5000),
        ),
    ]
