# Generated by Django 3.2.23 on 2024-01-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20240129_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
