# Generated by Django 3.2.23 on 2024-01-29 10:27

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('news', '0007_auto_20240129_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_draft',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, null=True)),
                ('content', tinymce.models.HTMLField(max_length=5000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('is_up_for_review', models.BooleanField(null=True)),
                ('is_approved', models.BooleanField(default=False, null=True)),
                ('is_up_for_deletion', models.BooleanField(default=False, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('draft_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.news')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
