# Generated by Django 3.2.23 on 2024-01-29 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('news', '0009_comment_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='is_news',
        ),
        migrations.AddField(
            model_name='like',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='like',
            name='is_dislike',
            field=models.BooleanField(default=False),
        ),
    ]
