# Generated by Django 3.2.23 on 2024-01-30 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_userprofile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
