# Generated by Django 3.2.23 on 2024-01-30 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20240130_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_draft',
            name='is_approved',
        ),
    ]
