# Use an official Python runtime as a parent image
FROM python:3.7.9

# Set environment variables
ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE mysite.settings

# Create and set the working directory
WORKDIR /app

# Copy the requirements file into the container at /app
COPY ./app/requirement.txt /app/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirement.txt
# Copy the current directory contents into the container at /app
COPY ./app /app/

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Define the command to run on container start
# Run the Django development server

